export const ROUTES = {
  PUBLIC: {
    LANDING: '/',
    FAQ: '/faq',
    DOCS: '/docs',
    CONTACT: '/contact',
    REGISTER: '/register',
    VERIFY_EMAIL: '/verify-email',
    LOGIN: '/login',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
  },
  DASHBOARD: '/dashboard',
  ACCOUNT: {
    PASSWORD: '/account/security/password',
    TWO_FACTOR: '/account/security/2fa',
    SESSIONS: '/account/security/sessions',
  },
  PROJECTS: {
    LIST: '/projects',
    OVERVIEW: (id = ':projectId') => `/projects/${id}`,
    NEW: '/projects/new',
    DELETE: (id = ':projectId') => `/projects/${id}/delete`,
    UPLOAD: (id = ':projectId') => `/projects/${id}/upload`,
    SCREENS: (id = ':projectId') => `/projects/${id}/screens`,
    CONVERT: (projectId = ':projectId', screenId = ':screenId') => `/projects/${projectId}/screens/${screenId}/convert`,
    BULK_CONVERT: (id = ':projectId') => `/projects/${id}/screens/bulk-convert`,
    RESULT: (projectId = ':projectId', screenId = ':screenId') => `/projects/${projectId}/screens/${screenId}/result`,
    PREVIEW: (projectId = ':projectId', screenId = ':screenId') => `/projects/${projectId}/screens/${screenId}/preview`,
    MAPPING: (projectId = ':projectId', screenId = ':screenId') => `/projects/${projectId}/screens/${screenId}/mapping`,
    REVIEW: (projectId = ':projectId', screenId = ':screenId') => `/projects/${projectId}/screens/${screenId}/review`,
    EXPORT: (id = ':projectId') => `/projects/${id}/export`,
    DIAGNOSTICS: (id = ':projectId') => `/projects/${id}/diagnostics`,
  },
  BILLING: {
    USAGE: '/billing/usage',
    PRICING: '/billing/pricing',
    SUBSCRIPTION: '/billing/subscription',
    TRIAL: '/billing/trial',
  },
};

