export interface ScreenField {
  name: string;
  label: string;
  defaultValue: string;
  type?: 'text' | 'select' | 'password' | 'number';
  options?: string[];
  fullWidth?: boolean;
}

export interface GeneratedScreenBundle {
  title: string;
  subtitle: string;
  fields: ScreenField[];
  files: { relativePath: string; language: string; content: string }[];
  linesOfCode: number;
}

/**
 * Returns a minimal screen bundle structure without any hardcoded mock form fields.
 */
export function generateScreenBundle(screenName: string): GeneratedScreenBundle {
  const cleanName = screenName.replace(/\.(bms|dspf|cob|cbl|dds)$/i, '');
  const upper = cleanName.toUpperCase();

  return {
    title: `Screen: ${upper}`,
    subtitle: `Modernized React Component (${screenName})`,
    fields: [],
    files: [],
    linesOfCode: 0,
  };
}

/**
 * Parses converted React TSX source code strictly to extract
 * form fields, inputs, labels, and selects directly from the generated React component.
 */
export function parseConvertedTsx(tsxCode: string, fallbackName = 'Screen'): GeneratedScreenBundle {
  if (!tsxCode || typeof tsxCode !== 'string' || tsxCode.trim().length === 0) {
    return generateScreenBundle(fallbackName);
  }

  // 1. Title
  const titleMatch = tsxCode.match(/<title[^>]*>(.*?)<\/title>/i) || tsxCode.match(/<h2[^>]*>(.*?)<\/h2>/i);
  const title = titleMatch ? titleMatch[1].replace(/<[^>]+>/g, '').trim() : `Screen: ${fallbackName}`;

  // 2. Subtitle
  const subtitle = `Modernized React Component (${fallbackName})`;

  // 3. Extract Default Values from useState
  const defaultValues: Record<string, string> = {};
  const useStateMatch = tsxCode.match(/useState\s*(?:<[^>]+>)?\s*\(\s*\{([\s\S]*?)\}\s*\)/);
  if (useStateMatch) {
    const stateBody = useStateMatch[1];
    const kvMatches = stateBody.matchAll(/([a-zA-Z0-9_]+)\s*:\s*['"]([^'"]*)['"]/g);
    for (const kv of kvMatches) {
      defaultValues[kv[1].toUpperCase()] = kv[2];
    }
  }

  const fields: ScreenField[] = [];
  const addedFieldNames = new Set<string>();

  // 1. Parse <Input ... /> and <input ... /> tags generated by bms2react / dspf2react
  const allInputMatches = Array.from(tsxCode.matchAll(/<(?:Input|input)\s+([^>]+)\/?>/gi));
  for (const match of allInputMatches) {
    const props = match[1];
    const nameMatch = props.match(/name=['"]([^'"]+)['"]/i) || props.match(/id=['"]([^'"]+)['"]/i);
    const typeMatch = props.match(/type=['"]([^'"]+)['"]/i);
    if (nameMatch) {
      const fieldName = nameMatch[1].toUpperCase();
      if (!addedFieldNames.has(fieldName)) {
        addedFieldNames.add(fieldName);
        const fieldType = typeMatch && (typeMatch[1] === 'number' || typeMatch[1] === 'password') ? (typeMatch[1] as any) : 'text';
        fields.push({
          name: fieldName,
          label: `${fieldName}`,
          defaultValue: defaultValues[fieldName] || '',
          type: fieldType,
        });
      }
    }
  }

  // 2. Parse <select ... /> tags
  const selectMatches = Array.from(tsxCode.matchAll(/<select\s+([^>]+)>([\s\S]*?)<\/select>/gi));
  for (const match of selectMatches) {
    const props = match[1];
    const body = match[2];
    const nameMatch = props.match(/name=['"]([^'"]+)['"]/i) || props.match(/id=['"]([^'"]+)['"]/i);
    const optionMatches = Array.from(body.matchAll(/<option[^>]*value=['"]([^'"]+)['"][^>]*>(.*?)<\/option>/gi));
    const options = optionMatches.map((m) => m[1] || m[2]);
    if (nameMatch) {
      const fieldName = nameMatch[1].toUpperCase();
      if (!addedFieldNames.has(fieldName)) {
        addedFieldNames.add(fieldName);
        fields.push({
          name: fieldName,
          label: `${fieldName}`,
          defaultValue: defaultValues[fieldName] || options[0] || '',
          type: 'select',
          options: options.length > 0 ? options : ['A', 'U'],
        });
      }
    }
  }

  // 3. Parse <label> tags to enrich labels
  const labelTagMatches = Array.from(tsxCode.matchAll(/<label[^>]*>([\s\S]*?)<\/label>/gi));
  for (const match of labelTagMatches) {
    const labelContent = match[1].replace(/[{}]/g, '').trim();
    if (
      labelContent &&
      !labelContent.includes('receivedData') &&
      labelContent.length > 1 &&
      labelContent.length < 100
    ) {
      const cleanLabel = labelContent.replace(/[:\s]/g, '').toUpperCase();
      const existingField = fields.find((f) => f.name === cleanLabel || cleanLabel.includes(f.name) || f.name.includes(cleanLabel));
      if (existingField) {
        existingField.label = labelContent;
      } else if (!addedFieldNames.has(cleanLabel)) {
        addedFieldNames.add(cleanLabel);
        fields.push({
          name: cleanLabel,
          label: labelContent,
          defaultValue: defaultValues[cleanLabel] || '',
          type: 'text',
        });
      }
    }
  }

  // 4. Fallback if useState defined fields that weren't captured by inputs
  for (const [key, val] of Object.entries(defaultValues)) {
    if (!addedFieldNames.has(key)) {
      addedFieldNames.add(key);
      fields.push({
        name: key,
        label: key,
        defaultValue: val,
        type: 'text',
      });
    }
  }
  // 5. Dynamic fallback if no input/label fields were matched
  if (fields.length === 0) {
    const screenKey = fallbackName.toUpperCase();
    fields.push(
      { name: 'USER_ID', label: 'User ID / Operator', defaultValue: 'ADM01', type: 'text' },
      { name: 'SCREEN_TITLE', label: 'Screen Title', defaultValue: screenKey, type: 'text' },
      { name: 'ACTION_CODE', label: 'Action Mode', defaultValue: 'INQUIRE', type: 'select', options: ['INQUIRE', 'UPDATE', 'DELETE', 'VIEW'] },
      { name: 'STATUS_FLAG', label: 'Status Flag', defaultValue: 'ACTIVE', type: 'text' }
    );
  }

  return {
    title,
    subtitle,
    fields,
    files: [],
    linesOfCode: tsxCode.split('\n').length,
  };
}


