export interface ScreenField {
  name: string;
  label: string;
  defaultValue: string;
  type?: 'text' | 'select' | 'password' | 'number';
  options?: string[];
  fullWidth?: boolean;
}

export interface GeneratedScreenBundle {
  title: string;
  subtitle: string;
  fields: ScreenField[];
  files: { relativePath: string; language: string; content: string }[];
  linesOfCode: number;
}

/**
 * Returns a minimal screen bundle structure without any hardcoded mock form fields.
 */
export function generateScreenBundle(screenName: string): GeneratedScreenBundle {
  const cleanName = screenName.replace(/\.(bms|dspf|cob|cbl|dds)$/i, '');
  const upper = cleanName.toUpperCase();

  return {
    title: `Screen: ${upper}`,
    subtitle: `Modernized React Component (${screenName})`,
    fields: [],
    files: [],
    linesOfCode: 0,
  };
}

/**
 * Parses converted React TSX source code strictly to extract
 * form fields, inputs, labels, and selects directly from the generated React component.
 */
export function parseConvertedTsx(tsxCode: string, fallbackName = 'Screen'): GeneratedScreenBundle {
  if (!tsxCode || typeof tsxCode !== 'string' || tsxCode.trim().length === 0) {
    return generateScreenBundle(fallbackName);
  }

  // 1. Title
  const titleMatch = tsxCode.match(/<title[^>]*>(.*?)<\/title>/i) || tsxCode.match(/<h2[^>]*>(.*?)<\/h2>/i);
  const title = titleMatch ? titleMatch[1].replace(/<[^>]+>/g, '').trim() : `Screen: ${fallbackName}`;

  // 2. Subtitle
  const subtitle = `Modernized React Component (${fallbackName})`;

  // 3. Extract Default Values from useState
  const defaultValues: Record<string, string> = {};
  const useStateMatch = tsxCode.match(/useState\s*(?:<[^>]+>)?\s*\(\s*\{([\s\S]*?)\}\s*\)/);
  if (useStateMatch) {
    const stateBody = useStateMatch[1];
    const kvMatches = stateBody.matchAll(/([a-zA-Z0-9_]+)\s*:\s*['"]([^'"]*)['"]/g);
    for (const kv of kvMatches) {
      defaultValues[kv[1].toUpperCase()] = kv[2];
    }
  }

  const fields: ScreenField[] = [];

  // Parse <Input ... /> tags generated by bms2react / dspf2react
  const inputTagMatches = Array.from(tsxCode.matchAll(/<Input\s+([^>]+)\/?>/gi));
  for (const match of inputTagMatches) {
    const props = match[1];
    const nameMatch = props.match(/name=['"]([^'"]+)['"]/i) || props.match(/id=['"]([^'"]+)['"]/i);
    const typeMatch = props.match(/type=['"]([^'"]+)['"]/i);
    if (nameMatch) {
      const fieldName = nameMatch[1].toUpperCase();
      const fieldType = typeMatch && typeMatch[1] === 'number' ? 'number' : 'text';
      fields.push({
        name: fieldName,
        label: `${fieldName}`,
        defaultValue: defaultValues[fieldName] || '',
        type: fieldType,
      });
    }
  }

  // Parse standard <label> tags
  const labelTagMatches = Array.from(tsxCode.matchAll(/<label[^>]*>([\s\S]*?)<\/label>/gi));
  for (const match of labelTagMatches) {
    const labelContent = match[1].replace(/[{}]/g, '').trim();
    if (labelContent && !labelContent.includes('receivedData') && labelContent.length < 100) {
      const fieldName = `LABEL_${fields.length + 1}`;
      fields.push({
        name: fieldName,
        label: labelContent,
        defaultValue: labelContent,
        type: 'text',
      });
    }
  }

  return {
    title,
    subtitle,
    fields,
    files: [],
    linesOfCode: tsxCode.split('\n').length,
  };
}


